language: python
dist: xenial
cache: pip
python:
- '3.6'
- '3.7'
install:
- pip install zstd~=1.4.9
- pip install git+https://github.com/XENONnT/straxen
- pip install -r requirements.txt
script:
- python setup.py test
