
import strax

DETECTOR_PREFIXES = {
    'XENONnT': 'fax_tpc',
    'XENONnT_neutron_veto': 'fax_nveto',
}

FAX_DEFAULTS = {
    's1_model_type': None,
    's2_luminescence_model': None,
    'enable_gas_gap_warping': None,
    'enable_pmt_afterpulses': None,
    'enable_electron_afterpulses': None,
    'enable_noise': None,
    'field_distortion_on': None,
    'field_distortion_model': None,
    'enable_field_dependencies': None,
    'url_base': None,
    'photon_area_distribution': None,
    's1_pattern_map': None,
    's2_pattern_map': None,
    's1_lce_correction_map': None,
    's2_correction_map': None,
    'photon_ap_cdfs': None,
    's2_luminescence': None,
    'gas_gap_map': None,
    'field_dependencies_map': None,
    'temperature': None,
    'pressure': None,
    'lxe_dielectric_constant': None,
    'tpc_length': None,
    'tpc_radius': None,
    'anode_wire_radius': None,
    'anode_field_domination_distance': None,
    'elr_gas_gap_length': None,
    'gate_to_anode_distance': None,
    'drift_field': None,
    'anode_voltage': None,
    'diffusion_constant_longitudinal': None,
    'diffusion_constant_transverse': None,
    'drift_time_gate': None,
    'drift_velocity_liquid': None,
    'singlet_fraction_gas': None,
    'singlet_lifetime_gas': None,
    'singlet_lifetime_liquid': None,
    'triplet_lifetime_gas': None,
    'triplet_lifetime_liquid': None,
    's1_ER_alpha_singlet_fraction': None,
    's1_ER_primary_singlet_fraction': None,
    's1_ER_recombination_fraction': None,
    's1_ER_recombination_time': None,
    's1_ER_secondary_singlet_fraction': None,
    's1_NR_singlet_fraction': None,
    'maximum_recombination_time': None,
    's1_decay_spread': None,
    's1_decay_time': None,
    's1_detection_efficiency': None,
    's2_mean_area_fraction_top': None,
    's2_aft_sigma': None,
    's2_aft_skewness': None,
    's2_secondary_sc_gain': None,
    's2_time_spread': None,
    'electron_extraction_yield': None,
    'electron_lifetime_liquid': None,
    'electron_trapping_time': None,
    'gas_drift_velocity_slope': None,
    'p_double_pe_emision': None,
    'pe_pulse_ts': None,
    'pe_pulse_ys': None,
    'pmt_ap_modifier': None,
    'pmt_ap_t_modifier': None,
    'pmt_pulse_time_rounding': None,
    'pmt_transit_time_mean': None,
    'pmt_transit_time_spread': None,
    'photoelectric_modifier': None,
    'photoelectric_p': None,
    'photoelectric_t_center': None,
    'photoelectric_t_spread': None,
    'photoionization_modifier': None,
    'sample_duration': None,
    'samples_after_pulse_center': None,
    'samples_before_pulse_center': None,
    'samples_to_store_after': None,
    'samples_to_store_before': None,
    'pmt_circuit_load_resistor': None,
    'external_amplification': None,
    'high_energy_deamplification_factor': None,
    'trigger_window': None,
    'digitizer_bits': None,
    'digitizer_reference_baseline': None,
    'digitizer_voltage_range': None,
    'special_thresholds': None,
    'zle_threshold': None,

}

TPC_FAX_OPTIONS = (strax.Option(f"{DETECTOR_PREFIXES['XENONnT']}_{k}", default=v) for k,v in FAX_DEFAULTS.items())
NVETO_FAX_OPTIONS = (strax.Option(f"{DETECTOR_PREFIXES['XENONnT_neutron_veto']}_{k}", default=v) for k,v in FAX_DEFAULTS.items())
