# Lets upload wfsim to PyPi to make it pip instalable
# Mostly based on https://github.com/marketplace/actions/pypi-publish
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      # Setup steps
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install wheel

      - name: Build package
        run: python setup.py sdist bdist_wheel

      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
